### ISSUE TITLE
Error on enabling arnold plugin

### ISSUE THREAD

**Issue by vitos23** [ForgeXYZ/Arnold-For-Blender#14]
I get an error on enabling plugin.

`ARNOLD_HOME env found
Setting Arnold path to: D:\Arnold Renderer\bin
Exception in module register(): D:\Program Files\blender-2.80.0\2.80\scripts\addons\barnold\__init__.py
Traceback (most recent call last):
  File "D:\Program Files\blender-2.80.0\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "D:\Program Files\blender-2.80.0\2.80\scripts\addons\barnold\__init__.py", line 164, in register
    from . import nodes
  File "D:\Program Files\blender-2.80.0\2.80\scripts\addons\barnold\nodes.py", line 31, in <module>
    import barnold.ui as ui
  File "D:\Program Files\blender-2.80.0\2.80\scripts\addons\barnold\ui.py", line 19, in <module>
    import barnold.engine as engine
  File "D:\Program Files\blender-2.80.0\2.80\scripts\addons\barnold\engine\__init__.py", line 22, in <module>
    import arnold
ModuleNotFoundError: No module named 'arnold'`

**Comment by furby-tm** [comment]
Please see this issue: https://github.com/tyler-furby/Arnold-For-Blender/issues/13 and let me know if you're still having issues.

**Comment by furby-tm** [comment]
Specifically this comment: https://github.com/tyler-furby/Arnold-For-Blender/issues/13#issuecomment-449461713

**Comment by vitos23** [comment]
Same error

**Comment by furby-tm** [comment]
Care to jump on discord so I can help you out? https://discord.gg/WNdNXzZ
