### ISSUE TITLE
ImportError: cannot import name 'PresetMenu' from 'bl_operators.presets'

### ISSUE THREAD

**Issue by starthlw** [ForgeXYZ/Arnold-For-Blender#19]
I install the arnold in blender 2.82 as branch:REWRITE/README.md , but there are some problems:

> bpy.data.window_managers["WinMan"].addon_filter = 'Render'
>bpy.context.object.name = "Cube"
>bpy.context.space_data.context = 'RENDER'
>bpy.context.scene.render.engine = 'CYCLES'
>Traceback (most recent call last):
>  File "D:\ ...\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\__init__.py", line 164, in register
    from . import nodes
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\nodes.py", line 31, in <module>
    import barnold.ui as ui
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\ui.py", line 8, in <module>
    from bl_operators.presets import PresetMenu
ImportError: cannot import name 'PresetMenu' from 'bl_operators.presets' (D:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\startup\bl_operators\presets.py)

>Traceback (most recent call last):
  File "D:\ ...\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\__init__.py", line 161, in register
    addon_preferences.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\addon_preferences.py", line 31, in register
    bpy.utils.register_class(ArnoldAddonPreferences)
ValueError: register_class(...): already registered as a subclass 'ArnoldAddonPreferences'

>Traceback (most recent call last):
  File "D:\ ...\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\__init__.py", line 161, in register
    addon_preferences.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\addon_preferences.py", line 31, in register
    bpy.utils.register_class(ArnoldAddonPreferences)
ValueError: register_class(...): already registered as a subclass 'ArnoldAddonPreferences'

>Traceback (most recent call last):
  File "D:\ ... \Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\__init__.py", line 161, in register
    addon_preferences.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\addon_preferences.py", line 31, in register
    bpy.utils.register_class(ArnoldAddonPreferences)
ValueError: register_class(...): already registered as a subclass 'ArnoldAddonPreferences'

>Traceback (most recent call last):
  File "D:\ ...\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\__init__.py", line 161, in register
    addon_preferences.register()
  File "D:\ ...\Blender 2.82\2.82\scripts\addons\barnold\addon_preferences.py", line 31, in register
    bpy.utils.register_class(ArnoldAddonPreferences)
ValueError: register_class(...): already registered as a subclass 'ArnoldAddonPreferences'
`
Who knows how to solve those problems? thank you very much!

**Comment by melMass** [comment]
The code in this repo is an early implementation  that has been since rewritten from scratch by @tyler-furby  and his team.

It should come up relatively soon with Arnold 6 support and more features than the original idea, but to be honest it’s “about to be release” for more than a year but they have recently updated the Readme again so I have hope.

Also it will not be free
